// <auto-generated />
using BooksSharingOnlineAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksSharingOnlineAPI.Migrations
{
    [DbContext(typeof(BookModelContext))]
    partial class BookModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BooksSharingOnlineAPI.Models.BookModel", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BookUrl")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FrontPageUrl")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.ToTable("BookModels");
                });
#pragma warning restore 612, 618
        }
    }
}
